<?php

/**
 * ContentBlockCurrentVersionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginContentBlockCurrentVersionTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ContentBlockCurrentVersionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ContentBlockCurrentVersion');
  }

  /**
   * Find the current version of a Content block
   *
   * @param int $id
   * @param string $lang
   * @return ContentBlockCurrentVersion
   */
  public function findCurrentVersion($id, $lang)
  {
    $query = $this->createQuery('v')
                  ->where('v.Content_block_id = ?', $id);

    if ($lang === null)
    {
      $query->addWhere('v.lang IS NULL');
    }
    else
    {
      $query->addWhere('v.lang = ?', $lang);
    }

    return $query->fetchOne();
  }
}