<?php

/**
 * ContentBlockCurrentVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    site_cms
 * @subpackage model
 * @author     Jo Carter
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginContentBlockCurrentVersion extends BaseContentBlockCurrentVersion 
{	
	/**
	 * Create unsaved current version for Content block
	 *
	 * @param ContentBlock $contentBlock
	 * @param string $lang
	 * @return ContentBlockCurrentVersion
	 */
	public static function createNew(ContentBlock $contentBlock, $lang) 
	{
		$contentBlockCurrentVersion = new ContentBlockCurrentVersion();
		$contentBlockCurrentVersion->lang = $lang;
		$contentBlockCurrentVersion->ContentBlock = $contentBlock;
		
		return $contentBlockCurrentVersion;
	}
}
