<?php

/**
 * PluginRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginRedirect extends BaseRedirect
{
  /**
   * Creates an unsaved Redirect object from the Sitetree
   *
   * @param Sitetree $sitetree
   * @return Redirect
   */
  public static function createFromSitetree($sitetree)
  {
    $redirect = new Redirect();
    $redirect->sitetree_id = $sitetree->id;

    return $redirect;
  }
}