<?php

/**
 * PluginSiteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSiteTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginSiteTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginSite');
  }

  /**
   * Get current site identifiers
   * 
   * @return array
   */
  public function getSiteIdentifiers()
  {
    $q = $this->createQuery('s')
              ->select('s.site');
              
    return $q->execute(null, Doctrine_Core::HYDRATE_SINGLE_SCALAR);
  }
}