<?php

/**
 * PluginRedirectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRedirectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginRedirectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRedirect');
    }
}