<?php

/**
 * PluginSite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    site_cms
 * @subpackage model
 * @author     Jo Carter
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSite extends BaseSite
{
  public function __toString()
  {
    return sprintf('%s (%s)', $this->name, $this->site);
  }
}