<?php

/**
 * ListingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginListingTable extends Doctrine_Table 
{ 
    /**
     * Returns an instance of this class.
     *
     * @return object ListingTable
     */
    public static function getInstance() 
	{
        return Doctrine_Core::getTable('Listing');
    }
}