<?php

/**
 * ContentGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginContentGroupTable extends Doctrine_Table 
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentGroupTable
     */
    public static function getInstance() 
	{
        return Doctrine_Core::getTable('ContentGroup');
    }
}