<?php

/**
 * PluginRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    site_cms
 * @subpackage model
 * @author     Jo Carter
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginRedirect extends BaseRedirect
{
  /**
   * Creates an unsaved Redirect object from the Sitetree
   *
   * @param Sitetree $sitetree
   * @return Redirect
   */
  public static function createFromSitetree($sitetree)
  {
    $redirect              = new Redirect();
    $redirect->sitetree_id = $sitetree->id;

    return $redirect;
  }
  
  /**
   * Create a copy of this redirect, exactly the same but linked to the given sitetree.
   *
   * @param Sitetree $copyToSitetree
   * @return Redirect
   */
  public function createCopy($copyToSitetree) 
  {
    $copy             = $this->copy(true);
    $copy->Sitetree   = $copyToSitetree;
    $copy->created_at = $copy->updated_at = null;
    
    $copy->save();
    
    return $copy;
  }
  
  /**
   * Handle redirect events
   * 
   * @static
   * @param siteEvent $event
   */
  public static function siteEventHandler(siteEvent $event)
  {
    if ($event->getName() == siteEvent::SITETREE_DELETE) 
    {
      // node has been deleted
      $sitetree = $event->getSubject();
   
      // handle delete - delete redirect link if sitetree node deleted (if not cascaded)
      $redirect = RedirectTable::getInstance()->findOneBySitetreeId($sitetree->id);
      if ($redirect) $redirect->delete();
    } 
    else if ($event->getName() == siteEvent::SITETREE_COPY) 
    {
      $copyFromSitetree = $event->getSubject();
      $params           = $event->getParameters();
      
      if (!$copyToSitetree = @$params['copyTo']) 
      {
        throw new sfException('No sitetree to copy to');
      }
      
      // get the redirect from the old Sitetree
      $fromRedirect = siteManager::getInstance()->loadItemFromSitetree('Redirect', $copyFromSitetree);
      
      if (!$fromRedirect) 
      {
        // there was no redirect at the old sitetree, maybe it hadn't been created yet.
        return;
      }
      
      $fromRedirect->createCopy($copyToSitetree);
    }
  }
}
