<?php

/**
 * PluginIframeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginIframeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginIframeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginIframe');
    }
}